---
# https://galaxy.ansible.com/ui/standalone/roles/geerlingguy/apache/
# ansible-galaxy role install geerlingguy.apache


# dom abr 28 18:42:34 rafael@rafael-VirtualBox ~/ansible-exercicies-github/ansible-exercises-by-groups-3-1-ansible/soluciones/ejercicio7$ ansible-playbook -i ../inventory apartado-6.yaml -u rafael --ask-become-pass
# PLAY RECAP *****************************************************************************************************
# localhost                  : ok=16   changed=6    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0  

- hosts: localhost
  become: true
  vars_files:
    - vars/main.yaml
  roles:
    - role: geerlingguy.apache
      become: true