---
- name: Pruebas con wait_for
  hosts: todos
  tasks:
    - name: Crear el archivo de bloqueo
      file:
        path: /tmp/bloqueo.lock
        owner: "{{ ansible_user_id }}"
        mode: '0775'
        state: touch

    - name: Esperar hasta que el archivo sea borrado
      wait_for:
        path: /tmp/bloqueo.lock
        state: absent

    - debug:
        msg: Ha salido del wait_for porque se ha borrado el archivo
...