- name: Guardar fecha actual
  hosts: all
  become: true
  vars:
    ruta: "/tmp/fechahora.data"
  tasks:
    - name: Almacenar fecha y hora en {{ ruta }}
      shell: date > {{ ruta }}

    - name: Verificar si el archivo se creó correctamente
      command: cat /tmp/fechahora.data
      register: file_content

    - debug:
        msg: "El contenido del archivo es: {{ file_content.stdout }}"
      when: file_content is succeeded