---
- name: Instalar Nginx y configurar el firewall
  hosts: grupo1
  become: yes
  tasks:
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
      tags:
        - nginx

    - name: Permitir paso a través de cortafuegos
      shell: ufw allow 'Nginx Full'
      ignore_errors: yes
      tags:
        - firewall

    - name: Verificar estado del cortafuegos
      shell: ufw status
      register: firewall_status
      tags:
        - firewall

    - name: Debug - Mostrar estado del cortafuegos
      debug:
        msg: "{{ firewall_status.stdout }}"
      tags:
        - firewall

    - name: Verificar si el servicio nginx está activo
      systemd:
        name: nginx
        state: started
      tags:
        - nginx

    - name: Verificar estado del servicio nginx
      systemd:
        name: nginx
        state: restarted
      register: nginx_status
      tags:
        - nginx

    - name: Debug - Mostrar estado del servicio nginx
      debug:
        msg: "{{ nginx_status }}"
      tags:
        - nginx
