---
- name: Ping al nodo1 para comprobar su disponibilidad
  hosts: nodo1
  tasks:
    - name: Ping al nodo1
      ping:

- name: Instalar Apache2 en el nodo1
  hosts: nodo1
  become: yes
  tasks:
    - name: Instalar Apache2
      apt:
        name: apache2
        state: present

- name: Comprobar si Apache2 est치 funcionando en el nodo1
  hosts: nodo1
  become: yes
  tasks:
    - name: Comprobar si Apache2 est치 en ejecuci칩n
      systemd:
        name: apache2
        state: started

- name: Instalar Mariadb con la ultima versi칩n
  hosts: nodo1
  become: yes
  tasks:
    - name: MariaDB
      apt:
        name: mariadb-server
        state: latest