---
- name: Validar si los paquetes están instalados
  hosts: todos
  tasks:
    - name: Lista de paquetes a verificar
      set_fact:
        packages_to_check: ['apache2', 'vim', 'nginx', 'filebeat']

    - name: Verificar si los paquetes están instalados
      shell: dpkg -l | grep -w "{{ item }}"
      loop: "{{ packages_to_check }}"
      register: package_checks
      ignore_errors: true

    - name: Mostrar resultados
      debug:
        msg: "{{ item.item }} está instalado: {{ 'SI' if item.rc == 0 else 'NO' }}"
      loop: "{{ package_checks.results }}"
