---
- name: Buscar archivos con m치s de 100 megabytes de tama침o
  hosts: todos
  tasks:
    - name: Buscar archivos con m치s de 100 megabytes de tama침o
      find:
        paths: /
        recurse: yes
        size: 100m
      register: large_files

    - name: Mostrar archivos encontrados
      debug:
        msg: "Archivo encontrado: {{ item.path }}"
      loop: "{{ large_files.files }}"
