---
- name: Verificar estado de servicios
  hosts: todos
  tasks:
    - name: Crear lista web_service
      set_fact:
        web_service: ['apache2', 'vsftpd']

    - name: Verificar si los servicios están iniciados
      service:
        name: "{{ item }}"
        state: started
      loop: "{{ web_service }}"
