---

- name: KAFKA | Install
  import_tasks: install.yml
  tags:
    - kafka_install

- name: KAFKA | Agent config
  import_tasks: agent.yml
  tags:
    - kafka_agents_config
  when: kafka_agents_config is defined

- name: KAFKA | Configure
  import_tasks: config.yml
  tags:
    - kafka_configure

- name: KAFKA | Service
  import_tasks: service.yml
  tags:
    - kafka_service

- name: KAFKA | Topics
  import_tasks: topics.yml
  run_once: true
  tags:
    - kafka_topics
