- name: Comprimir archivos con extensiones .log, .out y .txt
  hosts: todos
  vars:
    rutas: ['*.log','*.out','*.txt']
  tasks:
    - name: Comprimir archivos con exclusiones
      archive:
        path: /home/remoto/tomcat/logs/{{ item }}
        dest: /tmp/logs_comp.tar.gz
      loop: "{{ rutas }}"