---
- name: Instalación y arranque de apache2
  hosts: todos
  tasks:
    - name: Instalar apache2
      apt:
        name: apache2
        state: present

    - name: Iniciar servicio apache2
      service:
        name: apache2
        state: started
...