---
- name: Instalar paquetes con loop
  hosts: grupo1
  become: yes

  tasks:
    - name: Instalar paquetes
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - glances
        - git
        - vim
