---
- name: Crear usuarios y grupos en Ansible
  hosts: todos
  become: true

  vars:
    lista_usuarios:
      - Pedro
      - Juan
      - Maria
      - Ana
      - Antonio
      - Marta
      - Jose

    lista_grupos:
      - usuarios
      - admin
      - desarrollo
      - testing
      - produccion

  tasks:
    - name: Crear grupos
      group:
        name: "{{ item }}"
      loop: "{{ lista_grupos }}"

    - name: Crear usuarios
      user:
        name: "{{ item }}"
        groups: "{{ lista_grupos }}"
        state: present
      loop: "{{ lista_usuarios }}"