---
- name: Mostrar archivos en nodos Ubuntu
  hosts: todos
  become: yes

  tasks:
    - name: Verificar si el sistema operativo es Ubuntu
      
      block:
        - name: Ejecutar ls en / en diferentes formatos
          shell: "{{ item.command }}"
          register: ls_output
          with_items:
            - { command: "ls /" }
            - { command: "ls -a /" }
            - { command: "ls -la /" }

        - name: Mostrar resultado de ls en /, ls -a en /, ls -la en /
          debug:
            msg: "{{ item.stdout_lines }}"
          with_items: "{{ ls_output.results | default([]) }}"
      when: ansible_distribution == 'Ubuntu'
